#pragma once
#include <cstdint>

namespace agl
{
enum feature_type
{
	FEATURE_BLEND,
	FEATURE_COLOR_LOGIC_OP,
	FEATURE_CULL_FACE,
	FEATURE_DEBUG_OUTPUT,
	FEATURE_DEBUG_OUTPUT_SYNCHRONOUS,
	FEATURE_DEPTH_CLAMP,
	FEATURE_DEPTH_TEST,
	FEATURE_DITHER,
	FEATURE_FRAMEBUFFER_SRGB,
	FEATURE_LINE_SMOOTH,
	FEATURE_MULTISAMPLE,
	FEATURE_POLYGON_OFFSET_FILL,
	FEATURE_POLYGON_OFFSET_LINE,
	FEATURE_POLYGON_OFFSET_POINT,
	FEATURE_POLYGON_SMOOTH,
	FEATURE_PRIMITIVE_RESTART,
	FEATURE_PRIMITIVE_RESTART_FIXED_INDEX,
	FEATURE_RASTERIZER_DISCARD,
	FEATURE_SAMPLE_ALPHA_TO_COVERAGE,
	FEATURE_SAMPLE_ALPHA_TO_ONE,
	FEATURE_SAMPLE_COVERAGE,
	FEATURE_SAMPLE_SHADING,
	FEATURE_SAMPLE_MASK,
	FEATURE_SCISSOR_TEST,
	FEATURE_STENCIL_TEST,
	FEATURE_TEXTURE_CUBE_MAP_SEAMLESS,
	FEATURE_PROGRAM_POINT_SIZE,
};
}